### ISSUE TITLE
Rozdelit projekt na 3 casti

### ISSUE THREAD

**Issue by imouse82** [jiri-plhal/ares-api#1]
1. maven modul: Zavest databazovy modul.
2. maven modul: Zavest servisni modul (business vrstvu) - ta pouziva 1. modul.
3. maven modul: Spustitelna aplikace, ktera poskytuje WS - ta pouziva 2. modul.
4. maven modul: Spustitelna aplikace, ktera obsahuje klienta WS (3. modul) a poskytuje UX webove rozhrani.

**Comment by jiri-plhal** [comment]
Vytvoril jsem novy branch feature1 a v nem jsem projekt rozdelil na 3 moduly:
1) webapp - hlavni aplikace s vykreslenim na frontend
2) service - komunikacni vrstva pro pristup k datum
3) model - ziskavani a formatovani dat
Prosim o kontrolu, zda se to priblizuje tomu co pozadujete. V projektu zatim s databazi vubec nepracuji, vsechny udaje o firmach si dotazuji primo pres api aresu. Mohu to upravit např. tak, že při dotazu na IČO si firmu ulozim do databaze a potom uz taham udaje z mé databaze.

**Comment by imouse82** [comment]
Diky, vecer na to urcite mrknu a dam vam pripominky.
Pokud jde o databazovou vrstu, tak ji udelejte zatim prazdnou (jako modul)
v ramci techto zmen. Nicmene urcite pujdeme cestou, kterou navrhujete (ale
v samostatnem MR - muzete zalozit dalsi vetev, ktera navazuje na tu
feature1).
Nakonec bych si predstavoval tak, ze v ramci WS budete nabizet metodu na
synchro do databaze a jinak poskytovat data z databaze.


st 24. 2. 2021 v 11:52 odesílatel jiri-plhal <notifications@github.com>
napsal:

**Comment by jiri-plhal** [comment]
Dobry den,
tento ukol tedy mohu pozadovat za splneny?

**Comment by imouse82** [comment]
Jeste doplnuji sem pro uplnost. Je splneny a ukol uzaviram.
