### ISSUE TITLE
Vyuziti jpa nad datovou vrstvou

### ISSUE THREAD

**Issue by imouse82** [jiri-plhal/ares-api#13]
Do aplikace zavest datovou vrstvu, ktera bude umoznovat ulozeni firmy a jejich dat do databaze. Na frontendu bych definoval nova tlacitka na nacteni/ulozeno/aktualizaci z/do databaze (po vyhledani na detailu firmy). A pridal nejakou moznost prochazet a nacitat ulozene firmy (zrejme nova sekce).
Jako databazi pouzit postgres nebo nejakou pametovou databazi. pro napojeni prosim pouzijte jpa - konkretne hibernate.
V tomto ukolu se nebojte anotaci. Patricne pak okomentuju v CR. Databazova vrstva si o to rika ...
Muzete v ramci tohoto ukolu poresit i nasledujici body (nicmene muzeme poresit i jako samostatne podukoly):
1. Vyuzit verzovaci nastroj databaze (liquibase nebo ~~flydb~~ [flyway](https://www.baeldung.com/database-migrations-with-flyway))
1.2. integrace flyway se springem v ramci projektu (zamerit se v navodu na spring boot cast)
1.3. Definovat ve zmenovem skriptu inicializacni schema databaze (samozrejme to znamena, ze pro prvni spusteni si budete muset pripravit cistou databazi)
1.4. Deaktivovat vytvareni databaze pomoci hibernate/jpa a nechat to na flyway
2. Definovat test pro "repository" tridy s vyuzitim pametove databaze (
zonkyio/embedded-postgres)

**Comment by jiri-plhal** [comment]
Takze bych to provedl nasledujicim zpusobem:
- na strance s vyhledavanim firem bych udelal dve tlacitka pro vyhledavani firem (prvni vyhleda firmu v obchodnim rejstriku, druhe vyhleda firmu v databazi)
- na detailu firmy bych udelal dve tlacitka pro ulozeni a aktualizaci firmy v databazi
- databazi pouziju postgres
- v databazi budu mit 3 tabulky (Firma, Statutarni organ a Predmet Podnikani)

**Comment by imouse82** [comment]
Ano, to zni rozume. Db modul do samostatneho modulu

Dne st 3. 3. 2021 19:15 uživatel jiri-plhal <notifications@github.com>
napsal:

**Comment by imouse82** [comment]
Pokud to jde, tak davejte kod do repozitare probezne a pokud mate s necim problem, tak se klidne zeptejte (samozrejme s kodem). Jinak todle je takovy vetsi delsi ukol, takze bude trvat krapel dele.

**Comment by jiri-plhal** [comment]
Zdravim, muzete mi dat nejake podrobnosti o techto dvou ukolech:
1. Vyuzit verzovaci nastroj databaze (liquibase nebo flydb)
2. Definovat test pro "repository" tridy s vyuzitim pametove databaze (zonkyio/embedded-postgres)

Ad 1. Díval jsem se na flywaydb - zatím jsem si zkoušel spustit nějaké scripty přes příkaz "mvn flyway:migrate"
Ad 2. Na testování mám využít tuto knihovnu https://github.com/zonkyio/embedded-database-spring-test ?

**Comment by imouse82** [comment]
Ano, poslu nejake informace (doplnil jsem do zadani; vecer vyhlidnu jeste neco pro testovaci databazi), ale jeste nejsou zapracovane pripominky v te rozpracovane vetvi.

**Comment by imouse82** [comment]
Doplnil jsem nejake info k ukolu. Vse to vypada dobre. Pouze prosim upravte aplikaci tak, aby pozivala flyway primo pres spring boot. Neprochazi testy, protoze v konfiguraci chybi databaze a ta je vynucena kontextem. Je cas tedy pridat testovaci databazi. Pouzijte prosim Zonkyio (ano, to co jste odkazoval ve svem poslednim komentari).

**Comment by imouse82** [comment]
Aplikace vypada moc pekne. Az doresime tento ukol, tak se podivame jeste na WS (konretne na REST a openAPI - swagger). Zadam nasledne do dalsiho ukolu.

**Comment by imouse82** [comment]
Vypada to pekne. Zkuste prosim pokracovat dalsim ukolem. Ja v prubehu zitrka zpracuji a zadam ukol na zminovane WS.
