### ISSUE TITLE
Komunikace s business vrstvou pres WS

### ISSUE THREAD

**Issue by imouse82** [jiri-plhal/ares-api#17]
Upravit aplikaci tak, aby aplikacni (business) vrstvu obaloval novy projekt WS (pouzijte prosim REST a generujte [swaggerui](https://petstore.swagger.io/?_ga=2.229551828.970408529.1616070135-1048222272.1616070135) pomoci anotaci). Toto bude jedna springbootova spustitelna webova aplikace s http basi autentizaci (spring security).
Frontend bude druha samostatne spustitelna aplikace, ktera komunikuje s WS pomoci automaticky generovaneho klienta (z swaggerui/open api) - opet pujde a jde o springboot aplikaci.
To znamena, ze pro zprovozneni budete muset spoustet projekt s WS a nasledne frontend, ktery WS vola.

**Comment by jiri-plhal** [comment]
Jestli to tedy chápu dobře:
1) Vytvořím REST WS pro CRUD operace z databáze a pro načítání firem z rejstříku . Pomocí Swagger UI vygeneruji rozhraní, přes které mohu tyto operace provádět.
2) Druhá aplikace bude něco co tam mám teď, ale nebude to komunikovat se servisním modulem napřímo ale přes tu předchozí nově vytvořenou vrstvu?

**Comment by imouse82** [comment]
Ano, je to presne tak. To pak ve vetsich aplikacich umoznuje snazsi vydavani zmen a bezvypadkove nasazovani (High availbility) a dalsi.

**Comment by jiri-plhal** [comment]
Dobře a předpokládám, že pro REST WS mám vytvořit samostatný modul (tento modul bude využívat modul service a bude samostatně spustitelný). Nynější modul co tam mám - webapp bude potom využívat ten nově vytvořený modul. Je tomu tak?

**Comment by imouse82** [comment]
Presne tak.
