### ISSUE TITLE
Vyuzit lombok

### ISSUE THREAD

**Issue by imouse82** [jiri-plhal/ares-api#7]
Lombok jste uz pouzil pro "properties", pouzijte prosim i v dalsich tridach, at je v aplikaci co nejmene kodu, ktery lze "vynechat". Poskytnuty kod neni treba testovat a zjednodusuje cteni aplikace. Jde zejmena o domenove modely (takze: Firma, Statutarni organ). Pokuste se pouzit `@Builder`, `@Data` a i na dalsich mistech vyuzijte pripadne `@NonNull`.

**Comment by jiri-plhal** [comment]
Jestli to chapu spravne:
Tridy oznacim anotacemi @Builder a @Data (tady by pripadnes stacilo jen @Getter?), potom ziskam data z Ares a vytvorim instance pres metodu builder(). atd ?

**Comment by imouse82** [comment]
Je to tak. Pouzijte co nejvice anotaci z lomboku, abyste se zbavil psaneho kodu. Navic vyuzijte tu `@Builder`. A ano, `@Data` je jako by `@Getter` a `@Setter`, ale i dalsi `@EqualsAndHashCode` a `@ToString`.
